<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>NistParser.WPF</AssemblyName>
    <RootNamespace>NistParser.WPF</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NistParser\NistParser.csproj" />
  </ItemGroup>

</Project>
